// Generated by Wrangler by running `wrangler types`

interface Env {
	amigo: KVNamespace;
	TIMEZONE: "Europe/Bratislava";
	START_HOUR: "9";
	END_HOUR: "21";
}
declare module "*.nano" {
	const value: string;
	export default value;
}